version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      APP_NAME: Lumen
      APP_ENV: local
      APP_KEY: your-app-key-here
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      APP_TIMEZONE: UTC
      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL: ''
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
    networks:
      - lumen-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: lumen_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lumen-network

  db:
    image: mysql:8.0
    container_name: lumen_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lumen-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lumen_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - lumen-network

volumes:
  dbdata:

networks:
  lumen-network:
